name: Sync with Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nateraw/huggingface-sync-action@v0.0.5
        with:
          github_repo_id: ${{ github.repository }}
          huggingface_repo_id: "banarc/First_agent_template"  # Replace with your username and Space name
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_type: "space"
          space_sdk: "gradio"  # Or "streamlit", "static", etc.
